# Generated by Django 5.2.16 on 2026-07-25 13:17

import common.identifiers
import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geography', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.UUIDField(default=common.identifiers.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('address', models.TextField()),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, help_text='Point de retrait des courses ; origine du calcul de distance.', srid=4326)),
                ('phone', models.CharField(max_length=16)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='restaurants/')),
                ('is_active', models.BooleanField(default=True)),
                ('accepts_orders', models.BooleanField(default=True)),
                ('default_preparation_minutes', models.PositiveSmallIntegerField(default=20)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='restaurants', to='geography.deliveryzone')),
            ],
            options={
                'verbose_name': 'restaurant',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OpeningHours',
            fields=[
                ('id', models.UUIDField(default=common.identifiers.uuid7, editable=False, primary_key=True, serialize=False)),
                ('weekday', models.SmallIntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi'), (6, 'Dimanche')])),
                ('opens_at', models.TimeField()),
                ('closes_at', models.TimeField()),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opening_hours', to='restaurants.restaurant')),
            ],
            options={
                'verbose_name': "horaire d'ouverture",
                'verbose_name_plural': "horaires d'ouverture",
                'ordering': ['weekday', 'opens_at'],
            },
        ),
        migrations.AddIndex(
            model_name='restaurant',
            index=models.Index(fields=['location'], name='restaurants_locatio_be7514_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurant',
            index=models.Index(fields=['zone', 'is_active'], name='restaurants_zone_id_9f9828_idx'),
        ),
        migrations.AddConstraint(
            model_name='openinghours',
            constraint=models.UniqueConstraint(fields=('restaurant', 'weekday', 'opens_at'), name='opening_hours_unique_slot'),
        ),
        migrations.AddConstraint(
            model_name='openinghours',
            constraint=models.CheckConstraint(condition=models.Q(('opens_at', models.F('closes_at')), _negated=True), name='opening_hours_not_empty'),
        ),
    ]
