# Generated by Django 5.2.16 on 2026-07-26 11:56

import common.identifiers
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffMembership',
            fields=[
                ('id', models.UUIDField(default=common.identifiers.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_manager', models.BooleanField(default=False, help_text='Informatif : les droits viennent des permissions, pas de ce drapeau.')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_memberships', to='restaurants.restaurant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'rattachement du personnel',
                'verbose_name_plural': 'rattachements du personnel',
                'indexes': [models.Index(fields=['user'], name='restaurants_user_id_8207fc_idx'), models.Index(fields=['restaurant'], name='restaurants_restaur_ca646d_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'restaurant'), name='one_membership_per_user_and_restaurant')],
            },
        ),
    ]
