# Generated by Django 5.2.16 on 2026-07-29 18:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_staffmembership'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='staff',
            field=models.ManyToManyField(blank=True, related_name='restaurants', through='restaurants.StaffMembership', to=settings.AUTH_USER_MODEL),
        ),
    ]
