# Generated by Django 5.2.16 on 2026-08-05 20:25

import common.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_restaurant_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, storage=common.storage.banners, upload_to='restaurants/'),
        ),
    ]
