# Generated by Django 5.2.17 on 2026-09-08 06:57

import common.identifiers
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0002_alter_country_timezone'),
        ('restaurants', '0005_restaurant_lifecycle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaMembership',
            fields=[
                ('id', models.UUIDField(default=common.identifiers.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_areas', to='geography.city')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_areas', to='geography.country')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'rattachement de périmètre',
                'verbose_name_plural': 'rattachements de périmètre',
                'indexes': [models.Index(fields=['user'], name='restaurants_user_id_e15355_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('city__isnull', True), ('country__isnull', False)), models.Q(('city__isnull', False), ('country__isnull', True)), _connector='OR'), name='area_membership_exactly_one_target'), models.UniqueConstraint(condition=models.Q(('country__isnull', False)), fields=('user', 'country'), name='one_area_per_user_and_country'), models.UniqueConstraint(condition=models.Q(('city__isnull', False)), fields=('user', 'city'), name='one_area_per_user_and_city')],
            },
        ),
    ]
