# Generated by Django 5.2.16 on 2026-09-13 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_areamembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='stock_adjustment_ceiling_currency',
            field=models.CharField(blank=True, choices=[('EUR', 'EUR'), ('GHS', 'GHS'), ('GNF', 'GNF'), ('NGN', 'NGN'), ('USD', 'USD'), ('XAF', 'XAF'), ('XOF', 'XOF')], default=None, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='stock_adjustment_ceiling_minor',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
