# Generated by Django 5.2.16 on 2026-07-25 14:31

import common.identifiers
import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.UUIDField(default=common.identifiers.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('offered', 'Proposée'), ('accepted', 'Acceptée'), ('picked_up', 'Récupérée'), ('on_the_way', 'En route'), ('delivered', 'Livrée'), ('declined', 'Refusée'), ('cancelled', 'Annulée')], default='offered', max_length=16)),
                ('offered_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('picked_up_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('decline_reason', models.TextField(blank=True)),
                ('proof_of_delivery', models.ImageField(blank=True, null=True, upload_to='deliveries/')),
                ('courier_fee_minor', models.BigIntegerField(blank=True, null=True)),
                ('courier_fee_currency', models.CharField(blank=True, choices=[('EUR', 'EUR'), ('GHS', 'GHS'), ('GNF', 'GNF'), ('NGN', 'NGN'), ('USD', 'USD'), ('XAF', 'XAF'), ('XOF', 'XOF')], default=None, max_length=3, null=True)),
            ],
            options={
                'verbose_name': 'course',
                'ordering': ['-offered_at'],
            },
        ),
        migrations.CreateModel(
            name='CourierProfile',
            fields=[
                ('id', models.UUIDField(default=common.identifiers.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verification_status', models.CharField(choices=[('pending', 'En attente de validation'), ('approved', 'Validé'), ('rejected', 'Rejeté'), ('suspended', 'Suspendu')], db_index=True, default='pending', max_length=16)),
                ('verification_notes', models.TextField(blank=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('national_id_number', models.CharField(blank=True, max_length=64)),
                ('licence_number', models.CharField(blank=True, max_length=64)),
                ('vehicle_type', models.CharField(choices=[('motorcycle', 'Moto'), ('bicycle', 'Vélo'), ('car', 'Voiture'), ('scooter', 'Scooter')], max_length=16)),
                ('vehicle_plate', models.CharField(blank=True, max_length=32)),
                ('id_document', models.FileField(blank=True, null=True, upload_to='couriers/id/')),
                ('licence_document', models.FileField(blank=True, null=True, upload_to='couriers/licence/')),
                ('vehicle_document', models.FileField(blank=True, null=True, upload_to='couriers/vehicle/')),
                ('is_online', models.BooleanField(default=False, help_text='Bascule volontaire du livreur : accepte-t-il des courses ?')),
                ('last_location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('last_location_at', models.DateTimeField(blank=True, null=True)),
                ('deliveries_completed', models.PositiveIntegerField(default=0)),
                ('deliveries_cancelled', models.PositiveIntegerField(default=0)),
                ('rating_average', models.DecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('rating_count', models.PositiveIntegerField(default=0)),
                ('total_earnings_minor', models.BigIntegerField(blank=True, null=True)),
                ('total_earnings_currency', models.CharField(blank=True, choices=[('EUR', 'EUR'), ('GHS', 'GHS'), ('GNF', 'GNF'), ('NGN', 'NGN'), ('USD', 'USD'), ('XAF', 'XAF'), ('XOF', 'XOF')], default=None, max_length=3, null=True)),
            ],
            options={
                'verbose_name': 'profil livreur',
                'verbose_name_plural': 'profils livreurs',
            },
        ),
    ]
