# Generated by Django 5.2.16 on 2026-07-25 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('delivery', '0001_initial'),
        ('orders', '0001_initial'),
        ('restaurants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='orders.order'),
        ),
        migrations.AddField(
            model_name='courierprofile',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='couriers', to='restaurants.restaurant'),
        ),
        migrations.AddField(
            model_name='courierprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='courier_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courierprofile',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignment',
            name='courier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='delivery.courierprofile'),
        ),
        migrations.AddIndex(
            model_name='courierprofile',
            index=models.Index(fields=['restaurant', 'is_online', 'verification_status'], name='delivery_co_restaur_0bedeb_idx'),
        ),
        migrations.AddIndex(
            model_name='courierprofile',
            index=models.Index(fields=['last_location'], name='delivery_co_last_lo_f395c3_idx'),
        ),
        migrations.AddConstraint(
            model_name='courierprofile',
            constraint=models.CheckConstraint(condition=models.Q(('verification_status__in', ['approved', 'pending', 'rejected', 'suspended'])), name='courier_verification_in_enum'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['courier', '-offered_at'], name='delivery_as_courier_040e9a_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['order', 'status'], name='delivery_as_order_i_7311ae_idx'),
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['accepted', 'cancelled', 'declined', 'delivered', 'offered', 'on_the_way', 'picked_up'])), name='assignment_status_in_enum'),
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['declined', 'cancelled', 'delivered']), _negated=True), fields=('order',), name='one_active_assignment_per_order'),
        ),
    ]
