# Generated by Django 5.2.16 on 2026-07-31 06:18

import common.identifiers
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourierRating',
            fields=[
                ('id', models.UUIDField(default=common.identifiers.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True)),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='delivery.assignment')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courier_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'note de livreur',
                'verbose_name_plural': 'notes de livreurs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['customer', '-created_at'], name='delivery_co_custome_b5558b_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('score__gte', 1), ('score__lte', 5)), name='courier_rating_score_range')],
            },
        ),
    ]
