# Generated by Django 5.2.16 on 2026-08-01 18:44

import common.identifiers
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_courierrating'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourierShift',
            fields=[
                ('id', models.UUIDField(default=common.identifiers.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day_of_week', models.PositiveSmallIntegerField(help_text='Jour ISO : 1 = lundi, 7 = dimanche.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_available', models.BooleanField(default=True, help_text='Décoché plutôt que supprimé : une absence ponctuelle se lit dans le planning.')),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='delivery.courierprofile')),
            ],
            options={
                'verbose_name': 'créneau de livreur',
                'verbose_name_plural': 'créneaux de livreurs',
                'ordering': ['day_of_week', 'start_time'],
                'indexes': [models.Index(fields=['courier', 'day_of_week'], name='delivery_co_courier_b8650f_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('day_of_week__gte', 1), ('day_of_week__lte', 7)), name='courier_shift_day_range'), models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='courier_shift_window_ordered'), models.UniqueConstraint(fields=('courier', 'day_of_week', 'start_time'), name='courier_shift_unique_start')],
            },
        ),
    ]
