# Generated by Django 5.2.16 on 2026-08-05 20:25

import common.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_couriershift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='proof_of_delivery',
            field=models.ImageField(blank=True, null=True, storage=common.storage.courier_documents, upload_to='deliveries/'),
        ),
        migrations.AlterField(
            model_name='courierprofile',
            name='id_document',
            field=models.FileField(blank=True, null=True, storage=common.storage.courier_documents, upload_to='couriers/id/'),
        ),
        migrations.AlterField(
            model_name='courierprofile',
            name='licence_document',
            field=models.FileField(blank=True, null=True, storage=common.storage.courier_documents, upload_to='couriers/licence/'),
        ),
        migrations.AlterField(
            model_name='courierprofile',
            name='vehicle_document',
            field=models.FileField(blank=True, null=True, storage=common.storage.courier_documents, upload_to='couriers/vehicle/'),
        ),
    ]
