# Generated by Django 5.2.16 on 2026-09-07 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_alter_assignment_proof_of_delivery_and_more'),
        ('orders', '0004_idempotencykey_completed_at'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('accepted', 'picked_up', 'on_the_way'))), fields=('courier',), name='one_engaged_assignment_per_courier'),
        ),
    ]
