# Generated by Django 5.2.16 on 2026-09-19 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0007_courierprofile_service_zones'),
    ]

    operations = [
        migrations.AddField(
            model_name='courierprofile',
            name='id_document_expires_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courierprofile',
            name='licence_document_expires_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courierprofile',
            name='vehicle_document_expires_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
