# Generated by Django 5.2.16 on 2026-09-20 22:09

import common.identifiers
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0008_expiration_des_pieces'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentReminder',
            fields=[
                ('id', models.UUIDField(default=common.identifiers.uuid7, editable=False, primary_key=True, serialize=False)),
                ('piece', models.CharField(max_length=32)),
                ('expires_on', models.DateField()),
                ('threshold_days', models.PositiveSmallIntegerField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_reminders', to='delivery.courierprofile')),
            ],
            options={
                'verbose_name': "rappel d'expiration envoyé",
                'verbose_name_plural': "rappels d'expiration envoyés",
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['courier', 'expires_on'], name='delivery_do_courier_f3b467_idx')],
                'constraints': [models.UniqueConstraint(fields=('courier', 'piece', 'expires_on', 'threshold_days'), name='document_reminder_once')],
            },
        ),
    ]
