# Generated by Django 5.2.16 on 2026-07-25 13:17

import common.identifiers
import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geography', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPreference',
            fields=[
                ('id', models.UUIDField(default=common.identifiers.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dietary_restrictions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), blank=True, default=list, help_text='Ex. vegetarian, vegan, halal, gluten_free.', size=None)),
                ('allergens', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), blank=True, default=list, help_text='Signalés au restaurant sur chaque commande.', size=None)),
                ('marketing_push_enabled', models.BooleanField(default=True)),
                ('marketing_email_enabled', models.BooleanField(default=True)),
                ('preferred_language', models.CharField(default='fr', max_length=5)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'préférences client',
                'verbose_name_plural': 'préférences clients',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=common.identifiers.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(help_text='Nom donné par le client, ex. « Maison ».', max_length=50)),
                ('kind', models.CharField(choices=[('home', 'Domicile'), ('work', 'Travail'), ('other', 'Autre')], default='other', max_length=8)),
                ('recipient_name', models.CharField(blank=True, max_length=150)),
                ('recipient_phone', models.CharField(blank=True, help_text='Si différent du titulaire du compte — livraison à un tiers.', max_length=16, validators=[django.core.validators.RegexValidator(message='Format E.164 attendu.', regex='^\\+[1-9]\\d{7,14}$')])),
                ('line1', models.CharField(max_length=200)),
                ('line2', models.CharField(blank=True, max_length=200)),
                ('landmark', models.CharField(blank=True, help_text='Point de repère : « en face de la pharmacie Bel Air ».', max_length=200)),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('delivery_instructions', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='addresses', to='geography.city')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'adresse',
                'ordering': ['-is_default', '-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='profiles_ad_user_id_3e1133_idx'), models.Index(fields=['location'], name='profiles_ad_locatio_2d202e_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('user',), name='one_default_address_per_user')],
            },
        ),
    ]
