# Generated by Django 5.2.16 on 2026-07-25 14:31

import common.identifiers
import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('restaurants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=common.identifiers.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(help_text='Référence courte communiquée au client et au livreur.', max_length=12, unique=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmée'), ('preparing', 'En préparation'), ('ready', 'Prête'), ('picked_up', 'Récupérée'), ('on_the_way', 'En route'), ('delivered', 'Livrée'), ('cancelled', 'Annulée')], db_index=True, default='pending', max_length=16)),
                ('delivery_address_line', models.TextField()),
                ('delivery_landmark', models.CharField(blank=True, max_length=200)),
                ('delivery_location', models.JSONField(help_text="{'lat': …, 'lon': …} figé à la commande.")),
                ('delivery_instructions', models.TextField(blank=True)),
                ('recipient_name', models.CharField(max_length=150)),
                ('recipient_phone', models.CharField(max_length=16)),
                ('payment_method', models.CharField(choices=[('mobile_money', 'Mobile Money'), ('cash', 'Espèces à la livraison'), ('wallet', 'Portefeuille'), ('card', 'Carte bancaire')], max_length=16)),
                ('promo_code', models.CharField(blank=True, max_length=32)),
                ('placed_at', models.DateTimeField(auto_now_add=True)),
                ('estimated_delivery_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('subtotal_minor', models.BigIntegerField()),
                ('subtotal_currency', models.CharField(choices=[('EUR', 'EUR'), ('GHS', 'GHS'), ('GNF', 'GNF'), ('NGN', 'NGN'), ('USD', 'USD'), ('XAF', 'XAF'), ('XOF', 'XOF')], default=None, max_length=3)),
                ('delivery_fee_minor', models.BigIntegerField()),
                ('delivery_fee_currency', models.CharField(choices=[('EUR', 'EUR'), ('GHS', 'GHS'), ('GNF', 'GNF'), ('NGN', 'NGN'), ('USD', 'USD'), ('XAF', 'XAF'), ('XOF', 'XOF')], default=None, max_length=3)),
                ('discount_minor', models.BigIntegerField()),
                ('discount_currency', models.CharField(choices=[('EUR', 'EUR'), ('GHS', 'GHS'), ('GNF', 'GNF'), ('NGN', 'NGN'), ('USD', 'USD'), ('XAF', 'XAF'), ('XOF', 'XOF')], default=None, max_length=3)),
                ('total_minor', models.BigIntegerField()),
                ('total_currency', models.CharField(choices=[('EUR', 'EUR'), ('GHS', 'GHS'), ('GNF', 'GNF'), ('NGN', 'NGN'), ('USD', 'USD'), ('XAF', 'XAF'), ('XOF', 'XOF')], default=None, max_length=3)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='restaurants.restaurant')),
            ],
            options={
                'verbose_name': 'commande',
                'ordering': ['-placed_at'],
            },
        ),
        migrations.CreateModel(
            name='IdempotencyKey',
            fields=[
                ('id', models.UUIDField(default=common.identifiers.uuid7, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=64)),
                ('endpoint', models.CharField(max_length=120)),
                ('response_status', models.PositiveSmallIntegerField()),
                ('response_body', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idempotency_keys', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='orders.order')),
            ],
            options={
                'verbose_name': "clé d'idempotence",
                'verbose_name_plural': "clés d'idempotence",
            },
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.UUIDField(default=common.identifiers.uuid7, editable=False, primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=120)),
                ('item_image', models.URLField(blank=True)),
                ('quantity', models.PositiveSmallIntegerField()),
                ('options', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
                ('unit_price_minor', models.BigIntegerField()),
                ('unit_price_currency', models.CharField(choices=[('EUR', 'EUR'), ('GHS', 'GHS'), ('GNF', 'GNF'), ('NGN', 'NGN'), ('USD', 'USD'), ('XAF', 'XAF'), ('XOF', 'XOF')], default=None, max_length=3)),
                ('line_total_minor', models.BigIntegerField()),
                ('line_total_currency', models.CharField(choices=[('EUR', 'EUR'), ('GHS', 'GHS'), ('GNF', 'GNF'), ('NGN', 'NGN'), ('USD', 'USD'), ('XAF', 'XAF'), ('XOF', 'XOF')], default=None, max_length=3)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_lines', to='catalog.menuitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='orders.order')),
            ],
            options={
                'verbose_name': 'ligne de commande',
                'verbose_name_plural': 'lignes de commande',
            },
        ),
        migrations.CreateModel(
            name='OrderStatusEvent',
            fields=[
                ('id', models.UUIDField(default=common.identifiers.uuid7, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmée'), ('preparing', 'En préparation'), ('ready', 'Prête'), ('picked_up', 'Récupérée'), ('on_the_way', 'En route'), ('delivered', 'Livrée'), ('cancelled', 'Annulée')], max_length=16)),
                ('to_status', models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmée'), ('preparing', 'En préparation'), ('ready', 'Prête'), ('picked_up', 'Récupérée'), ('on_the_way', 'En route'), ('delivered', 'Livrée'), ('cancelled', 'Annulée')], max_length=16)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, help_text='Nul si la transition vient du système (webhook, tâche planifiée).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_events', to='orders.order')),
            ],
            options={
                'verbose_name': 'événement de statut',
                'verbose_name_plural': 'événements de statut',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['restaurant', 'status', '-placed_at'], name='orders_orde_restaur_c8e41a_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer', '-placed_at'], name='orders_orde_custome_7b68ab_idx'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['cancelled', 'confirmed', 'delivered', 'on_the_way', 'pending', 'picked_up', 'preparing', 'ready'])), name='order_status_in_enum'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('subtotal_minor__gte', 0), ('delivery_fee_minor__gte', 0), ('discount_minor__gte', 0), ('total_minor__gte', 0)), name='order_amounts_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('discount_minor__lte', django.db.models.expressions.CombinedExpression(models.F('subtotal_minor'), '+', models.F('delivery_fee_minor')))), name='order_discount_within_bounds'),
        ),
        migrations.AddConstraint(
            model_name='idempotencykey',
            constraint=models.UniqueConstraint(fields=('user', 'endpoint', 'key'), name='idempotency_key_unique_per_user'),
        ),
        migrations.AddIndex(
            model_name='orderline',
            index=models.Index(fields=['order'], name='orders_orde_order_i_44a8a5_idx'),
        ),
        migrations.AddConstraint(
            model_name='orderline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='order_line_quantity_positive'),
        ),
        migrations.AddIndex(
            model_name='orderstatusevent',
            index=models.Index(fields=['order', 'created_at'], name='orders_orde_order_i_1e3f4d_idx'),
        ),
    ]
