# Generated by Django 5.2.16 on 2026-07-26 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_reference_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_fee_gross_currency',
            field=models.CharField(blank=True, choices=[('EUR', 'EUR'), ('GHS', 'GHS'), ('GNF', 'GNF'), ('NGN', 'NGN'), ('USD', 'USD'), ('XAF', 'XAF'), ('XOF', 'XOF')], default=None, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_fee_gross_minor',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
