# Generated by Django 5.2.16 on 2026-07-26 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_delivery_fee_gross_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='idempotencykey',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
