# Generated by Django 5.2.16 on 2026-09-17 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_geographie_reprise'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount_paid_currency',
            field=models.CharField(blank=True, choices=[('EUR', 'EUR'), ('GHS', 'GHS'), ('GNF', 'GNF'), ('NGN', 'NGN'), ('USD', 'USD'), ('XAF', 'XAF'), ('XOF', 'XOF')], default=None, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='amount_paid_minor',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
