# Generated by Django 5.2.17 on 2026-09-25 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_variantes'),
        ('orders', '0009_notes_internes'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.variant'),
        ),
        migrations.AddField(
            model_name='orderline',
            name='variant_name',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
