# Generated by Django 5.2.16 on 2026-09-12 22:09

import common.identifiers
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0006_alter_menuitem_image'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.UUIDField(default=common.identifiers.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('menu_item', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipe', to='catalog.menuitem')),
                ('option', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipe', to='catalog.option')),
            ],
            options={
                'verbose_name': 'recette',
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.UUIDField(default=common.identifiers.uuid7, editable=False, primary_key=True, serialize=False)),
                ('quantity_base', models.BigIntegerField()),
                ('quantity_dimension', models.CharField(choices=[('mass', 'mass'), ('volume', 'volume'), ('count', 'count')], max_length=6)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipe_lines', to='inventory.ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='production.recipe')),
            ],
            options={
                'verbose_name': 'ligne de recette',
                'verbose_name_plural': 'lignes de recette',
                'ordering': ['ingredient__name'],
            },
        ),
        migrations.AddConstraint(
            model_name='recipe',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('menu_item__isnull', False), ('option__isnull', True)), models.Q(('menu_item__isnull', True), ('option__isnull', False)), _connector='OR'), name='recipe_targets_exactly_one'),
        ),
        migrations.AddIndex(
            model_name='recipeingredient',
            index=models.Index(fields=['ingredient'], name='production__ingredi_ef8aca_idx'),
        ),
        migrations.AddConstraint(
            model_name='recipeingredient',
            constraint=models.UniqueConstraint(fields=('recipe', 'ingredient'), name='one_recipe_line_per_ingredient'),
        ),
        migrations.AddConstraint(
            model_name='recipeingredient',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_base', 0), _negated=True), name='recipe_line_quantity_not_zero'),
        ),
    ]
