# Generated by Django 5.2.16 on 2026-07-25 13:17

import common.identifiers
import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=common.identifiers.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField(blank=True)),
                ('permissions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('analytics.read', 'Consulter les statistiques et rapports'), ('catalog.read', 'Consulter le catalogue et les stocks'), ('catalog.write', 'Créer et modifier articles, catégories et options'), ('couriers.approve', 'Valider ou rejeter un dossier livreur'), ('couriers.read', 'Consulter les livreurs et leur position'), ('couriers.suspend', 'Suspendre un livreur'), ('customers.block', 'Bloquer ou débloquer un compte client'), ('customers.read', 'Consulter les comptes clients'), ('notifications.send', 'Envoyer une notification ciblée'), ('orders.assign_courier', 'Affecter un livreur à une commande'), ('orders.cancel', 'Annuler une commande'), ('orders.read', 'Consulter les commandes'), ('orders.refund', "Rembourser tout ou partie d'une commande"), ('orders.update_status', "Faire avancer le statut d'une commande"), ('promotions.read', 'Consulter les promotions'), ('promotions.write', 'Créer et modifier des promotions'), ('restaurants.read', 'Consulter les établissements et leurs zones'), ('restaurants.write', 'Créer et modifier établissements et zones'), ('roles.read', 'Consulter les rôles et permissions'), ('roles.write', 'Créer et modifier des rôles')], max_length=64), blank=True, default=list, size=None)),
                ('is_system', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'rôle',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=common.identifiers.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=16, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Le numéro doit être au format international E.164, par exemple +22890123456.', regex='^\\+[1-9]\\d{7,14}$')])),
                ('full_name', models.CharField(max_length=150)),
                ('user_type', models.CharField(choices=[('customer', 'Client'), ('courier', 'Livreur'), ('staff', 'Personnel')], db_index=True, default='customer', max_length=16)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('is_active', models.BooleanField(default=True, help_text='Décoché plutôt que supprimé : les commandes passées y renvoient.')),
                ('is_superuser', models.BooleanField(default=False)),
                ('email_verified_at', models.DateTimeField(blank=True, null=True)),
                ('phone_verified_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('roles', models.ManyToManyField(blank=True, related_name='users', to='accounts.role')),
            ],
            options={
                'verbose_name': 'utilisateur',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=common.identifiers.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(max_length=512, unique=True)),
                ('platform', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android'), ('web', 'Web')], max_length=8)),
                ('last_used_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'appareil',
                'indexes': [models.Index(fields=['user', '-last_used_at'], name='accounts_de_user_id_faca3e_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['user_type', 'is_active'], name='accounts_us_user_ty_029544_idx'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('is_superuser', False), ('user_type', 'staff'), _connector='OR'), name='superuser_is_staff'),
        ),
    ]
