# Generated by Django 5.2.16 on 2026-08-05 20:25

import common.storage
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_role_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='permissions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('analytics.read', 'Consulter les statistiques et rapports'), ('catalog.read', 'Consulter le catalogue et les stocks'), ('catalog.write', 'Créer et modifier articles, catégories et options'), ('couriers.approve', 'Valider ou rejeter un dossier livreur'), ('couriers.read', 'Consulter les livreurs et leur position'), ('couriers.suspend', 'Suspendre un livreur'), ('couriers.write', 'Créer un compte livreur'), ('customers.block', 'Bloquer ou débloquer un compte client'), ('customers.read', 'Consulter les comptes clients'), ('gamification.read', 'Consulter succès, badges et défis'), ('gamification.write', 'Créer et modifier succès, badges et défis'), ('loyalty.read', 'Consulter le catalogue de récompenses'), ('loyalty.write', 'Créer et modifier des récompenses'), ('notifications.send', 'Envoyer une notification ciblée'), ('orders.assign_courier', 'Affecter un livreur à une commande'), ('orders.cancel', 'Annuler une commande'), ('orders.read', 'Consulter les commandes'), ('orders.refund', "Rembourser tout ou partie d'une commande"), ('orders.update_status', "Faire avancer le statut d'une commande"), ('promotions.read', 'Consulter les promotions'), ('promotions.write', 'Créer et modifier des promotions'), ('restaurants.read', 'Consulter les établissements et leurs zones'), ('restaurants.write', 'Créer et modifier établissements et zones'), ('roles.read', 'Consulter les rôles, les permissions et les comptes du personnel'), ('roles.write', 'Créer et modifier des rôles, et les attribuer au personnel')], max_length=64), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, storage=common.storage.user_media, upload_to='avatars/'),
        ),
    ]
