# Generated by Django 5.2.16 on 2026-09-02 14:51

import common.identifiers
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_role_permissions_alter_user_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('id', models.UUIDField(default=common.identifiers.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purpose', models.CharField(choices=[('account_verification', 'Vérification du compte'), ('password_reset', 'Réinitialisation du mot de passe')], db_index=True, max_length=32)),
                ('code_hash', models.CharField(max_length=128)),
                ('sent_to', models.EmailField(max_length=254)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'code de vérification',
                'verbose_name_plural': 'codes de vérification',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'purpose', '-created_at'], name='accounts_ve_user_id_f57e3f_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('consumed_at__isnull', True)), fields=('user', 'purpose'), name='one_live_code_per_purpose')],
            },
        ),
    ]
