# Generated by Django 5.2.16 on 2026-09-19 09:55

import common.identifiers
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_permissions_versements_support_journal'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerNote',
            fields=[
                ('id', models.UUIDField(default=common.identifiers.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_notes_about', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'note interne sur un client',
                'verbose_name_plural': 'notes internes sur un client',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['customer', 'created_at'], name='accounts_cu_custome_051cc5_idx')],
            },
        ),
    ]
