# Generated by Django 5.2.16 on 2026-09-20 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditentry',
            name='scope_restaurant_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
