# Generated by Django 5.2.16 on 2026-07-26 22:40

import common.identifiers
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0004_idempotencykey_completed_at'),
        ('restaurants', '0002_staffmembership'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PointsAccount',
            fields=[
                ('id', models.UUIDField(default=common.identifiers.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('balance', models.PositiveIntegerField(default=0)),
                ('lifetime_earned', models.PositiveIntegerField(default=0)),
                ('lifetime_spent', models.PositiveIntegerField(default=0)),
                ('last_activity_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='points_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'compte de fidélité',
                'verbose_name_plural': 'comptes de fidélité',
            },
        ),
        migrations.CreateModel(
            name='PointsEntry',
            fields=[
                ('id', models.UUIDField(default=common.identifiers.uuid7, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('earned', 'Gagnés sur une commande'), ('spent', 'Dépensés en récompense'), ('expired', 'Expirés'), ('adjusted', 'Ajustement manuel')], db_index=True, max_length=16)),
                ('delta', models.IntegerField()),
                ('balance_after', models.PositiveIntegerField()),
                ('description', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='loyalty.pointsaccount')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points_entries', to='orders.order')),
            ],
            options={
                'verbose_name': 'mouvement de points',
                'verbose_name_plural': 'mouvements de points',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.UUIDField(default=common.identifiers.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('kind', models.CharField(choices=[('discount', 'Remise sur une commande'), ('free_delivery', 'Livraison offerte')], max_length=16)),
                ('points_cost', models.PositiveIntegerField()),
                ('discount_minor', models.PositiveIntegerField(default=0)),
                ('discount_currency', models.CharField(default='XOF', max_length=3)),
                ('validity_days', models.PositiveSmallIntegerField(default=30)),
                ('is_active', models.BooleanField(default=True)),
                ('restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='restaurants.restaurant')),
            ],
            options={
                'verbose_name': 'récompense',
                'ordering': ['points_cost'],
            },
        ),
        migrations.CreateModel(
            name='RewardRedemption',
            fields=[
                ('id', models.UUIDField(default=common.identifiers.uuid7, editable=False, primary_key=True, serialize=False)),
                ('points_spent', models.PositiveIntegerField()),
                ('promotion_code', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('entry', models.OneToOneField(help_text="Le débit qui a payé cet échange. Sans lui, l'échange n'a pas été payé.", on_delete=django.db.models.deletion.PROTECT, related_name='redemption', to='loyalty.pointsentry')),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='loyalty.reward')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_redemptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'échange de récompense',
                'verbose_name_plural': 'échanges de récompense',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='pointsentry',
            index=models.Index(fields=['account', '-created_at'], name='loyalty_poi_account_9ce54d_idx'),
        ),
        migrations.AddConstraint(
            model_name='pointsentry',
            constraint=models.CheckConstraint(condition=models.Q(('delta', 0), _negated=True), name='points_entry_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='pointsentry',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'earned')), fields=('account', 'order'), name='one_earning_per_order'),
        ),
        migrations.AddConstraint(
            model_name='reward',
            constraint=models.CheckConstraint(condition=models.Q(('points_cost__gt', 0)), name='reward_cost_is_positive'),
        ),
        migrations.AddConstraint(
            model_name='reward',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'discount'), _negated=True), ('discount_minor__gt', 0), _connector='OR'), name='reward_discount_is_set'),
        ),
        migrations.AddIndex(
            model_name='rewardredemption',
            index=models.Index(fields=['user', '-created_at'], name='loyalty_rew_user_id_eaf107_idx'),
        ),
    ]
