# Generated by Django 5.2.17 on 2026-09-24 14:01

import common.identifiers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0002_subscription_subscriptionpayment_subscriptionplan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyTier',
            fields=[
                ('id', models.UUIDField(default=common.identifiers.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=40, unique=True)),
                ('threshold', models.PositiveIntegerField(help_text='Points cumulés gagnés à partir desquels le palier est atteint.', unique=True)),
            ],
            options={
                'verbose_name': 'palier de fidélité',
                'verbose_name_plural': 'paliers de fidélité',
                'ordering': ['threshold'],
            },
        ),
    ]
