# Generated by Django 5.2.16 on 2026-07-27 00:37

import common.identifiers
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.UUIDField(default=common.identifiers.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='🏆', max_length=32)),
                ('condition_type', models.CharField(choices=[('orders_count', 'Nombre de commandes livrées'), ('total_spent_minor', 'Total dépensé (unité mineure)')], max_length=32)),
                ('condition_value', models.PositiveIntegerField(help_text="Seuil à atteindre, dans l'unité de `condition_type`.")),
                ('points_reward', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'succès',
                'verbose_name_plural': 'succès',
                'constraints': [models.CheckConstraint(condition=models.Q(('condition_value__gt', 0)), name='achievement_condition_positive')],
            },
        ),
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.UUIDField(default=common.identifiers.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='🏅', max_length=32)),
                ('points_required', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'badge',
                'constraints': [models.CheckConstraint(condition=models.Q(('points_required__gt', 0)), name='badge_threshold_positive')],
            },
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.UUIDField(default=common.identifiers.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('challenge_type', models.CharField(choices=[('daily', 'Quotidien'), ('weekly', 'Hebdomadaire'), ('monthly', 'Mensuel'), ('special', 'Spécial')], max_length=16)),
                ('condition_type', models.CharField(choices=[('orders_count', 'Nombre de commandes livrées'), ('total_spent_minor', 'Total dépensé (unité mineure)')], default='orders_count', max_length=32)),
                ('target_value', models.PositiveIntegerField()),
                ('reward_points', models.PositiveIntegerField(default=0)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'défi',
                'ordering': ['-starts_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('target_value__gt', 0)), name='challenge_target_positive'), models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='challenge_window_ordered')],
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.UUIDField(default=common.identifiers.uuid7, editable=False, primary_key=True, serialize=False)),
                ('progress', models.PositiveIntegerField(default=0)),
                ('is_unlocked', models.BooleanField(default=False)),
                ('unlocked_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocks', to='gamification.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'progression de succès',
                'verbose_name_plural': 'progressions de succès',
                'indexes': [models.Index(fields=['user', 'is_unlocked'], name='gamificatio_user_id_69f856_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'achievement'), name='one_progress_per_user')],
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.UUIDField(default=common.identifiers.uuid7, editable=False, primary_key=True, serialize=False)),
                ('is_unlocked', models.BooleanField(default=False)),
                ('unlocked_at', models.DateTimeField(blank=True, null=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocks', to='gamification.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'badge obtenu',
                'verbose_name_plural': 'badges obtenus',
                'constraints': [models.UniqueConstraint(fields=('user', 'badge'), name='one_badge_state_per_user')],
            },
        ),
        migrations.CreateModel(
            name='UserChallenge',
            fields=[
                ('id', models.UUIDField(default=common.identifiers.uuid7, editable=False, primary_key=True, serialize=False)),
                ('progress', models.PositiveIntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='gamification.challenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'participation à un défi',
                'verbose_name_plural': 'participations aux défis',
                'constraints': [models.UniqueConstraint(fields=('user', 'challenge'), name='one_participation_per_user')],
            },
        ),
    ]
