# Generated by Django 5.2.16 on 2026-07-27 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievement',
            options={'ordering': ['condition_value'], 'verbose_name': 'succès', 'verbose_name_plural': 'succès'},
        ),
        migrations.AlterModelOptions(
            name='badge',
            options={'ordering': ['points_required'], 'verbose_name': 'badge'},
        ),
    ]
