# Generated by Django 5.2.16 on 2026-07-25 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carts', '0001_initial'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartline',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_lines', to='catalog.menuitem'),
        ),
        migrations.AddField(
            model_name='cartlineoption',
            name='line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='carts.cartline'),
        ),
        migrations.AddField(
            model_name='cartlineoption',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_selections', to='catalog.option'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['user', '-updated_at'], name='carts_cart_user_id_6c1a10_idx'),
        ),
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.UniqueConstraint(fields=('user', 'restaurant'), name='one_cart_per_user_and_restaurant'),
        ),
        migrations.AddIndex(
            model_name='cartline',
            index=models.Index(fields=['cart'], name='carts_cartl_cart_id_0d1796_idx'),
        ),
        migrations.AddConstraint(
            model_name='cartline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='cart_line_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='cartlineoption',
            constraint=models.UniqueConstraint(fields=('line', 'option'), name='one_selection_per_line_and_option'),
        ),
    ]
