# Generated by Django 5.2.17 on 2026-09-25 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_initial'),
        ('catalog', '0008_variantes'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartline',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.variant'),
        ),
    ]
