# Generated by Django 5.2.16 on 2026-07-26 19:17

import common.identifiers
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0002_staffmembership'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.UUIDField(default=common.identifiers.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='Saisi par le client. Comparé sans tenir compte de la casse.', max_length=32, unique=True)),
                ('description', models.TextField(blank=True)),
                ('kind', models.CharField(choices=[('percentage', 'Pourcentage du sous-total'), ('fixed', 'Montant fixe'), ('free_delivery', 'Livraison offerte')], max_length=16)),
                ('percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('usage_limit', models.PositiveIntegerField(blank=True, help_text='Quota global. Vide = illimité.', null=True)),
                ('usage_limit_per_user', models.PositiveIntegerField(blank=True, help_text='Quota par personne. Vide = illimité.', null=True)),
                ('used_count', models.PositiveIntegerField(default=0, editable=False)),
                ('is_active', models.BooleanField(default=True)),
                ('amount_minor', models.BigIntegerField(blank=True, null=True)),
                ('amount_currency', models.CharField(blank=True, choices=[('EUR', 'EUR'), ('GHS', 'GHS'), ('GNF', 'GNF'), ('NGN', 'NGN'), ('USD', 'USD'), ('XAF', 'XAF'), ('XOF', 'XOF')], default=None, max_length=3, null=True)),
                ('min_order_amount_minor', models.BigIntegerField(blank=True, null=True)),
                ('min_order_amount_currency', models.CharField(blank=True, choices=[('EUR', 'EUR'), ('GHS', 'GHS'), ('GNF', 'GNF'), ('NGN', 'NGN'), ('USD', 'USD'), ('XAF', 'XAF'), ('XOF', 'XOF')], default=None, max_length=3, null=True)),
                ('max_discount_minor', models.BigIntegerField(blank=True, null=True)),
                ('max_discount_currency', models.CharField(blank=True, choices=[('EUR', 'EUR'), ('GHS', 'GHS'), ('GNF', 'GNF'), ('NGN', 'NGN'), ('USD', 'USD'), ('XAF', 'XAF'), ('XOF', 'XOF')], default=None, max_length=3, null=True)),
                ('restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='restaurants.restaurant')),
            ],
            options={
                'verbose_name': 'promotion',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromotionRedemption',
            fields=[
                ('id', models.UUIDField(default=common.identifiers.uuid7, editable=False, primary_key=True, serialize=False)),
                ('order_id', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('discount_minor', models.BigIntegerField()),
                ('discount_currency', models.CharField(choices=[('EUR', 'EUR'), ('GHS', 'GHS'), ('GNF', 'GNF'), ('NGN', 'NGN'), ('USD', 'USD'), ('XAF', 'XAF'), ('XOF', 'XOF')], default=None, max_length=3)),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='promotions.promotion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_uses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'utilisation de promotion',
                'verbose_name_plural': 'utilisations de promotion',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['code'], name='promotions__code_e9f529_idx'),
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['is_active', 'starts_at', 'ends_at'], name='promotions__is_acti_37078e_idx'),
        ),
        migrations.AddConstraint(
            model_name='promotion',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='promotion_period_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='promotion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'percentage'), _negated=True), ('percentage__gt', 0), _connector='OR'), name='promotion_percentage_is_set'),
        ),
        migrations.AddConstraint(
            model_name='promotion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'fixed'), _negated=True), ('amount_minor__gt', 0), _connector='OR'), name='promotion_amount_is_set'),
        ),
        migrations.AddIndex(
            model_name='promotionredemption',
            index=models.Index(fields=['promotion', 'user'], name='promotions__promoti_5452ff_idx'),
        ),
        migrations.AddConstraint(
            model_name='promotionredemption',
            constraint=models.UniqueConstraint(fields=('promotion', 'order_id'), name='one_redemption_per_promotion_and_order'),
        ),
    ]
