# Generated by Django 5.2.16 on 2026-07-25 14:31

import common.identifiers
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SplitPayment',
            fields=[
                ('id', models.UUIDField(default=common.identifiers.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('completed', 'Encaissé'), ('failed', 'Échoué'), ('cancelled', 'Annulé'), ('refunded', 'Remboursé')], default='pending', max_length=16)),
                ('total_amount_minor', models.BigIntegerField()),
                ('total_amount_currency', models.CharField(choices=[('EUR', 'EUR'), ('GHS', 'GHS'), ('GNF', 'GNF'), ('NGN', 'NGN'), ('USD', 'USD'), ('XAF', 'XAF'), ('XOF', 'XOF')], default=None, max_length=3)),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='initiated_splits', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='split_payment', to='orders.order')),
            ],
            options={
                'verbose_name': 'paiement partagé',
                'verbose_name_plural': 'paiements partagés',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=common.identifiers.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('paydunya', 'PayDunya'), ('cash', 'Espèces à la livraison'), ('wallet', 'Portefeuille interne')], max_length=16)),
                ('provider_reference', models.CharField(max_length=128, unique=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('completed', 'Encaissé'), ('failed', 'Échoué'), ('cancelled', 'Annulé'), ('refunded', 'Remboursé')], db_index=True, default='pending', max_length=16)),
                ('payer_phone', models.CharField(blank=True, max_length=16)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('amount_minor', models.BigIntegerField()),
                ('amount_currency', models.CharField(choices=[('EUR', 'EUR'), ('GHS', 'GHS'), ('GNF', 'GNF'), ('NGN', 'NGN'), ('USD', 'USD'), ('XAF', 'XAF'), ('XOF', 'XOF')], default=None, max_length=3)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='orders.order')),
                ('payer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'transaction',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SplitShare',
            fields=[
                ('id', models.UUIDField(default=common.identifiers.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_name', models.CharField(max_length=150)),
                ('phone', models.CharField(blank=True, max_length=16)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('completed', 'Encaissé'), ('failed', 'Échoué'), ('cancelled', 'Annulé'), ('refunded', 'Remboursé')], default='pending', max_length=16)),
                ('amount_minor', models.BigIntegerField()),
                ('amount_currency', models.CharField(choices=[('EUR', 'EUR'), ('GHS', 'GHS'), ('GNF', 'GNF'), ('NGN', 'NGN'), ('USD', 'USD'), ('XAF', 'XAF'), ('XOF', 'XOF')], default=None, max_length=3)),
                ('participant', models.ForeignKey(blank=True, help_text="Nul si le participant n'a pas de compte — invité par lien.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='split_shares', to=settings.AUTH_USER_MODEL)),
                ('split', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='payments.splitpayment')),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='split_share', to='payments.transaction')),
            ],
            options={
                'verbose_name': 'part de paiement',
                'verbose_name_plural': 'parts de paiement',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.UUIDField(default=common.identifiers.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('completed', 'Encaissé'), ('failed', 'Échoué'), ('cancelled', 'Annulé'), ('refunded', 'Remboursé')], default='pending', max_length=16)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('amount_minor', models.BigIntegerField()),
                ('amount_currency', models.CharField(choices=[('EUR', 'EUR'), ('GHS', 'GHS'), ('GNF', 'GNF'), ('NGN', 'NGN'), ('USD', 'USD'), ('XAF', 'XAF'), ('XOF', 'XOF')], default=None, max_length=3)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='orders.order')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='payments.transaction')),
            ],
            options={
                'verbose_name': 'remboursement',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.UUIDField(default=common.identifiers.uuid7, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('paydunya', 'PayDunya'), ('cash', 'Espèces à la livraison'), ('wallet', 'Portefeuille interne')], max_length=16)),
                ('event_id', models.CharField(max_length=128)),
                ('payload', models.JSONField()),
                ('signature_verified', models.BooleanField(default=False)),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_error', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'événement de webhook',
                'verbose_name_plural': 'événements de webhook',
                'ordering': ['-received_at'],
                'constraints': [models.UniqueConstraint(fields=('provider', 'event_id'), name='webhook_event_unique_per_provider')],
            },
        ),
        migrations.AddConstraint(
            model_name='splitpayment',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['cancelled', 'completed', 'failed', 'pending', 'processing', 'refunded'])), name='split_status_in_enum'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['order', 'status'], name='payments_tr_order_i_028313_idx'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['cancelled', 'completed', 'failed', 'pending', 'processing', 'refunded'])), name='transaction_status_in_enum'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('amount_minor__gt', 0)), name='transaction_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='splitshare',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['cancelled', 'completed', 'failed', 'pending', 'processing', 'refunded'])), name='share_status_in_enum'),
        ),
        migrations.AddConstraint(
            model_name='splitshare',
            constraint=models.CheckConstraint(condition=models.Q(('amount_minor__gt', 0)), name='share_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='splitshare',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'completed'), _negated=True), ('transaction__isnull', False), _connector='OR'), name='settled_share_requires_transaction'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['order', '-created_at'], name='payments_re_order_i_9e1c29_idx'),
        ),
        migrations.AddConstraint(
            model_name='refund',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['cancelled', 'completed', 'failed', 'pending', 'processing', 'refunded'])), name='refund_status_in_enum'),
        ),
        migrations.AddConstraint(
            model_name='refund',
            constraint=models.CheckConstraint(condition=models.Q(('amount_minor__gt', 0)), name='refund_amount_positive'),
        ),
    ]
