# Generated by Django 5.2.16 on 2026-07-27 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_idempotencykey_completed_at'),
        ('payments', '0002_splitshare_share_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='orders.order'),
        ),
    ]
