# Generated by Django 5.2.16 on 2026-07-31 14:46

import common.identifiers
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_courierrating'),
        ('payments', '0003_alter_transaction_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.UUIDField(default=common.identifiers.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('completed', 'Encaissé'), ('failed', 'Échoué'), ('cancelled', 'Annulé'), ('refunded', 'Remboursé')], default='pending', max_length=16)),
                ('provider_reference', models.CharField(blank=True, max_length=128)),
                ('failure_reason', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('amount_minor', models.BigIntegerField()),
                ('amount_currency', models.CharField(choices=[('EUR', 'EUR'), ('GHS', 'GHS'), ('GNF', 'GNF'), ('NGN', 'NGN'), ('USD', 'USD'), ('XAF', 'XAF'), ('XOF', 'XOF')], default=None, max_length=3)),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='withdrawals', to='delivery.courierprofile')),
            ],
            options={
                'verbose_name': 'retrait',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['courier', '-created_at'], name='payments_wi_courier_a2612a_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['cancelled', 'completed', 'failed', 'pending', 'processing', 'refunded'])), name='withdrawal_status_in_enum'), models.CheckConstraint(condition=models.Q(('amount_minor__gt', 0)), name='withdrawal_amount_positive')],
            },
        ),
    ]
