# Generated by Django 5.2.16 on 2026-09-24 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_withdrawal_processed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='checkout_instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='checkout_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
