# Generated by Django 5.2.16 on 2026-09-12 10:17

import common.identifiers
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0006_areamembership'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.UUIDField(default=common.identifiers.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('dimension', models.CharField(choices=[('mass', 'Masse'), ('volume', 'Volume'), ('count', 'Dénombrement')], help_text="Ce que l'on mesure : une masse, un volume, ou des unités.", max_length=6)),
                ('allergens', models.JSONField(blank=True, default=list, help_text="Codes d'allergènes, hérités par tout plat dont la recette emploie cet ingrédient.")),
                ('is_active', models.BooleanField(default=True, help_text='Une référence inactive ne peut plus entrer en stock, mais son historique reste lisible.')),
            ],
            options={
                'verbose_name': 'ingrédient',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active', 'name'], name='inventory_i_is_acti_995d02_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('dimension__in', ('mass', 'volume', 'count'))), name='ingredient_dimension_in_enum')],
            },
        ),
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.UUIDField(default=common.identifiers.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('on_hand_base', models.BigIntegerField()),
                ('on_hand_dimension', models.CharField(choices=[('mass', 'mass'), ('volume', 'volume'), ('count', 'count')], max_length=6)),
                ('reserved_base', models.BigIntegerField()),
                ('reserved_dimension', models.CharField(choices=[('mass', 'mass'), ('volume', 'volume'), ('count', 'count')], max_length=6)),
                ('low_stock_threshold_base', models.BigIntegerField(blank=True, null=True)),
                ('low_stock_threshold_dimension', models.CharField(blank=True, choices=[('mass', 'mass'), ('volume', 'volume'), ('count', 'count')], max_length=6, null=True)),
                ('unit_cost_minor', models.BigIntegerField(blank=True, null=True)),
                ('unit_cost_currency', models.CharField(blank=True, choices=[('EUR', 'EUR'), ('GHS', 'GHS'), ('GNF', 'GNF'), ('NGN', 'NGN'), ('USD', 'USD'), ('XAF', 'XAF'), ('XOF', 'XOF')], default=None, max_length=3, null=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_items', to='inventory.ingredient')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_items', to='restaurants.restaurant')),
            ],
            options={
                'verbose_name': 'ligne de stock',
                'verbose_name_plural': 'lignes de stock',
                'ordering': ['ingredient__name'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=common.identifiers.uuid7, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('purchase', 'Achat'), ('receipt', 'Réception'), ('consumption', 'Consommation'), ('waste', 'Perte'), ('adjustment', 'Ajustement'), ('transfer', 'Transfert'), ('reservation', 'Réservation'), ('release', 'Libération')], max_length=12)),
                ('reason', models.TextField(blank=True, help_text='Obligatoire pour un ajustement ou une perte — voir le service.')),
                ('reference', models.CharField(blank=True, db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('quantity_base', models.BigIntegerField()),
                ('quantity_dimension', models.CharField(choices=[('mass', 'mass'), ('volume', 'volume'), ('count', 'count')], max_length=6)),
                ('unit_cost_minor', models.BigIntegerField(blank=True, null=True)),
                ('unit_cost_currency', models.CharField(blank=True, choices=[('EUR', 'EUR'), ('GHS', 'GHS'), ('GNF', 'GNF'), ('NGN', 'NGN'), ('USD', 'USD'), ('XAF', 'XAF'), ('XOF', 'XOF')], default=None, max_length=3, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL)),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.stockitem')),
            ],
            options={
                'verbose_name': 'mouvement de stock',
                'verbose_name_plural': 'mouvements de stock',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='stockitem',
            index=models.Index(fields=['restaurant', 'ingredient'], name='inventory_s_restaur_e2086b_idx'),
        ),
        migrations.AddIndex(
            model_name='stockitem',
            index=models.Index(fields=['restaurant', 'on_hand_base'], name='inventory_s_restaur_45d8a1_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockitem',
            constraint=models.UniqueConstraint(fields=('restaurant', 'ingredient'), name='one_stock_item_per_restaurant_and_ingredient'),
        ),
        migrations.AddConstraint(
            model_name='stockitem',
            constraint=models.CheckConstraint(condition=models.Q(('on_hand_base__gte', 0)), name='stock_item_on_hand_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='stockitem',
            constraint=models.CheckConstraint(condition=models.Q(('reserved_base__gte', 0)), name='stock_item_reserved_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='stockitem',
            constraint=models.CheckConstraint(condition=models.Q(('reserved_base__lte', models.F('on_hand_base'))), name='stock_item_reserved_within_on_hand'),
        ),
        migrations.AddConstraint(
            model_name='stockitem',
            constraint=models.CheckConstraint(condition=models.Q(('on_hand_dimension', models.F('reserved_dimension'))), name='stock_item_dimensions_agree'),
        ),
        migrations.AddConstraint(
            model_name='stockitem',
            constraint=models.CheckConstraint(condition=models.Q(('low_stock_threshold_base__isnull', True), ('low_stock_threshold_dimension', models.F('on_hand_dimension')), _connector='OR'), name='stock_item_threshold_dimension_agrees'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['stock_item', '-created_at'], name='inventory_s_stock_i_73796c_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['kind', '-created_at'], name='inventory_s_kind_79c19c_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['purchase', 'receipt', 'consumption', 'waste', 'adjustment', 'transfer', 'reservation', 'release'])), name='stock_movement_kind_in_enum'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_base', 0), _negated=True), name='stock_movement_quantity_not_zero'),
        ),
    ]
