# Generated by Django 5.2.16 on 2026-09-13 12:36

import common.identifiers
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdjustmentRequest',
            fields=[
                ('id', models.UUIDField(default=common.identifiers.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('purchase', 'Achat'), ('receipt', 'Réception'), ('consumption', 'Consommation'), ('waste', 'Perte'), ('adjustment', 'Ajustement'), ('transfer', 'Transfert'), ('reservation', 'Réservation'), ('release', 'Libération')], max_length=12)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'En attente de validation'), ('approved', 'Validée'), ('rejected', 'Refusée')], default='pending', max_length=8)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True)),
                ('request_key', models.CharField(blank=True, default='', max_length=64)),
                ('quantity_base', models.BigIntegerField()),
                ('quantity_dimension', models.CharField(choices=[('mass', 'mass'), ('volume', 'volume'), ('count', 'count')], max_length=6)),
                ('estimated_value_minor', models.BigIntegerField(blank=True, null=True)),
                ('estimated_value_currency', models.CharField(blank=True, choices=[('EUR', 'EUR'), ('GHS', 'GHS'), ('GNF', 'GNF'), ('NGN', 'NGN'), ('USD', 'USD'), ('XAF', 'XAF'), ('XOF', 'XOF')], default=None, max_length=3, null=True)),
            ],
            options={
                'verbose_name': 'demande de correction de stock',
                'verbose_name_plural': 'demandes de correction de stock',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='request_key',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.UniqueConstraint(condition=models.Q(('request_key', ''), _negated=True), fields=('request_key',), name='stock_movement_request_key_unique'),
        ),
        migrations.AddField(
            model_name='adjustmentrequest',
            name='decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_adjustments_decided', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adjustmentrequest',
            name='movement',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adjustment_request', to='inventory.stockmovement'),
        ),
        migrations.AddField(
            model_name='adjustmentrequest',
            name='requested_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_adjustments_requested', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adjustmentrequest',
            name='stock_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustment_requests', to='inventory.stockitem'),
        ),
        migrations.AddIndex(
            model_name='adjustmentrequest',
            index=models.Index(fields=['status', '-created_at'], name='inventory_a_status_526e60_idx'),
        ),
        migrations.AddIndex(
            model_name='adjustmentrequest',
            index=models.Index(fields=['stock_item', 'status'], name='inventory_a_stock_i_c79477_idx'),
        ),
        migrations.AddConstraint(
            model_name='adjustmentrequest',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['adjustment', 'waste'])), name='adjustment_request_kind_is_adjustment_or_waste'),
        ),
        migrations.AddConstraint(
            model_name='adjustmentrequest',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'approved', 'rejected'])), name='adjustment_request_status_in_enum'),
        ),
        migrations.AddConstraint(
            model_name='adjustmentrequest',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_base', 0), _negated=True), name='adjustment_request_quantity_not_zero'),
        ),
        migrations.AddConstraint(
            model_name='adjustmentrequest',
            constraint=models.CheckConstraint(condition=models.Q(('reason', ''), _negated=True), name='adjustment_request_reason_required'),
        ),
        migrations.AddConstraint(
            model_name='adjustmentrequest',
            constraint=models.CheckConstraint(condition=models.Q(('decided_by__isnull', True), models.Q(('decided_by', models.F('requested_by')), _negated=True), _connector='OR'), name='adjustment_request_four_eyes'),
        ),
        migrations.AddConstraint(
            model_name='adjustmentrequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('decided_at__isnull', True), ('movement__isnull', True), ('status', 'pending')), models.Q(('decided_at__isnull', False), ('movement__isnull', False), ('status', 'approved')), models.Q(('decided_at__isnull', False), ('movement__isnull', True), ('status', 'rejected')), _connector='OR'), name='adjustment_request_status_matches_traces'),
        ),
        migrations.AddConstraint(
            model_name='adjustmentrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('request_key', ''), _negated=True), fields=('request_key',), name='adjustment_request_key_unique'),
        ),
    ]
