# Generated by Django 5.2.16 on 2026-07-26 08:01

import apps.geography.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='timezone',
            field=models.CharField(default='UTC', max_length=64, validators=[apps.geography.models.validate_timezone]),
        ),
    ]
