# Generated by Django 5.2.17 on 2026-09-08 17:56

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0002_alter_country_timezone'),
        ('restaurants', '0006_areamembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='centroid',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='country',
            name='currency_symbol',
            field=models.CharField(blank=True, help_text='Par exemple FCFA. À défaut, le code ISO est affiché.', max_length=8),
        ),
        migrations.AddField(
            model_name='country',
            name='iso3_code',
            field=models.CharField(blank=True, help_text='Code ISO 3166-1 alpha-3, par exemple TGO.', max_length=3),
        ),
        migrations.AddField(
            model_name='deliveryzone',
            name='center',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='deliveryzone',
            name='priority',
            field=models.SmallIntegerField(default=0, help_text="À surface comparable, la priorité la plus haute l'emporte."),
        ),
        migrations.AddField(
            model_name='deliveryzone',
            name='radius_meters',
            field=models.PositiveIntegerField(blank=True, help_text='Rayon du disque, en mètres. Renseigné pour les zones circulaires seulement.', null=True, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(200000)]),
        ),
        migrations.AddField(
            model_name='deliveryzone',
            name='restaurant',
            field=models.ForeignKey(blank=True, help_text='Zone propre à un établissement. Vide, la zone vaut pour toute la ville.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='own_zones', to='restaurants.restaurant'),
        ),
        migrations.AddField(
            model_name='deliveryzone',
            name='shape',
            field=models.CharField(choices=[('circle', 'Cercle'), ('polygon', 'Polygone'), ('administrative', 'Zone administrative')], default='polygon', help_text='Avec quel outil le contour a été saisi — le contour reste un polygone.', max_length=16),
        ),
        migrations.AddIndex(
            model_name='deliveryzone',
            index=models.Index(fields=['restaurant', 'is_active'], name='zone_restaurant_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='deliveryzone',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('center__isnull', False), ('radius_meters__isnull', False), ('shape', 'circle')), models.Q(models.Q(('shape', 'circle'), _negated=True), ('center__isnull', True), ('radius_meters__isnull', True)), _connector='OR'), name='zone_circle_carries_center_and_radius'),
        ),
    ]
