# Generated by Django 5.2.16 on 2026-07-27 07:33

import common.identifiers
import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0004_idempotencykey_completed_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.UUIDField(default=common.identifiers.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('order', 'Commande'), ('payment', 'Paiement'), ('account', 'Compte'), ('delivery', 'Livraison'), ('other', 'Autre')], max_length=16)),
                ('subject', models.CharField(max_length=160)),
                ('description', models.TextField()),
                ('attachments', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), blank=True, default=list, size=None)),
                ('status', models.CharField(choices=[('open', 'Ouvert'), ('in_progress', 'En cours'), ('resolved', 'Résolu'), ('closed', 'Fermé')], default='open', max_length=16)),
                ('resolution', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ticket de support',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.UUIDField(default=common.identifiers.uuid7, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_messages', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='support.supportticket')),
            ],
            options={
                'verbose_name': 'message de support',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.UUIDField(default=common.identifiers.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('quality', 'Qualité'), ('delivery', 'Livraison'), ('service', 'Service'), ('other', 'Autre')], max_length=16)),
                ('subject', models.CharField(max_length=160)),
                ('description', models.TextField()),
                ('photos', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), blank=True, default=list, size=None)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('under_review', "En cours d'examen"), ('resolved', 'Résolue'), ('rejected', 'Rejetée')], default='pending', max_length=16)),
                ('resolution', models.TextField(blank=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='complaints', to='orders.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'réclamation',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='support_com_user_id_0727ee_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.UUIDField(default=common.identifiers.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.TextField()),
                ('items', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), help_text='Articles concernés, en clair.', size=None)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvée'), ('rejected', 'Rejetée'), ('refunded', 'Remboursée')], default='pending', max_length=16)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('refund_amount_minor', models.BigIntegerField()),
                ('refund_amount_currency', models.CharField(choices=[('EUR', 'EUR'), ('GHS', 'GHS'), ('GNF', 'GNF'), ('NGN', 'NGN'), ('USD', 'USD'), ('XAF', 'XAF'), ('XOF', 'XOF')], default=None, max_length=3)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_requests', to='orders.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'demande de retour',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='support_ret_user_id_8614bc_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('refund_amount_minor__gt', 0)), name='return_amount_positive')],
            },
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['user', '-created_at'], name='support_sup_user_id_7a4186_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['status'], name='support_sup_status_c35d7c_idx'),
        ),
    ]
