# Generated by Django 5.2.16 on 2026-09-18 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnrequest',
            name='resolution',
            field=models.TextField(blank=True),
        ),
    ]
