# Generated by Django 5.2.16 on 2026-07-30 00:28

import common.identifiers
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0003_menuitem_stock_quantity_menuitem_tracks_stock'),
        ('orders', '0004_idempotencykey_completed_at'),
        ('restaurants', '0003_restaurant_staff'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupCart',
            fields=[
                ('id', models.UUIDField(default=common.identifiers.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, help_text="Libellé libre — « Déjeuner de l'équipe ». Purement d'affichage.", max_length=120)),
                ('code', models.CharField(db_index=True, max_length=12, unique=True)),
                ('status', models.CharField(choices=[('open', 'Ouvert aux ajouts'), ('locked', 'Clos, en attente de confirmation'), ('confirmed', 'Confirmé en commande'), ('cancelled', 'Annulé'), ('expired', 'Échéance dépassée')], db_index=True, default='open', max_length=16)),
                ('closes_at', models.DateTimeField(db_index=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_group_carts', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_cart', to='orders.order')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_carts', to='restaurants.restaurant')),
            ],
            options={
                'verbose_name': 'panier collaboratif',
                'verbose_name_plural': 'paniers collaboratifs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupCartLine',
            fields=[
                ('id', models.UUIDField(default=common.identifiers.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
                ('group_cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='groupcarts.groupcart')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_cart_lines', to=settings.AUTH_USER_MODEL)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_cart_lines', to='catalog.menuitem')),
            ],
            options={
                'verbose_name': 'ligne de panier collaboratif',
                'verbose_name_plural': 'lignes de panier collaboratif',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupCartLineOption',
            fields=[
                ('id', models.UUIDField(default=common.identifiers.uuid7, editable=False, primary_key=True, serialize=False)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='groupcarts.groupcartline')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_cart_selections', to='catalog.option')),
            ],
            options={
                'verbose_name': 'option de ligne de panier collaboratif',
                'verbose_name_plural': 'options de ligne de panier collaboratif',
            },
        ),
        migrations.CreateModel(
            name='GroupCartMember',
            fields=[
                ('id', models.UUIDField(default=common.identifiers.uuid7, editable=False, primary_key=True, serialize=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('group_cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='groupcarts.groupcart')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_cart_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'participant',
                'ordering': ['joined_at'],
            },
        ),
        migrations.AddIndex(
            model_name='groupcart',
            index=models.Index(fields=['status', 'closes_at'], name='groupcarts__status_a1cba1_idx'),
        ),
        migrations.AddIndex(
            model_name='groupcart',
            index=models.Index(fields=['host', '-created_at'], name='groupcarts__host_id_1925f4_idx'),
        ),
        migrations.AddConstraint(
            model_name='groupcart',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['cancelled', 'confirmed', 'expired', 'locked', 'open'])), name='group_cart_status_in_enum'),
        ),
        migrations.AddIndex(
            model_name='groupcartline',
            index=models.Index(fields=['group_cart', 'member'], name='groupcarts__group_c_e1cd33_idx'),
        ),
        migrations.AddConstraint(
            model_name='groupcartline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='group_cart_line_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='groupcartlineoption',
            constraint=models.UniqueConstraint(fields=('line', 'option'), name='one_selection_per_group_line_and_option'),
        ),
        migrations.AddConstraint(
            model_name='groupcartmember',
            constraint=models.UniqueConstraint(fields=('group_cart', 'user'), name='one_membership_per_group_cart_and_user'),
        ),
    ]
