# Generated by Django 5.2.16 on 2026-07-31 12:32

import common.identifiers
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0004_idempotencykey_completed_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.UUIDField(default=common.identifiers.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('voice', 'Audio'), ('video', 'Vidéo')], default='voice', max_length=8)),
                ('status', models.CharField(choices=[('ringing', 'Sonne'), ('accepted', 'En cours'), ('declined', 'Refusé'), ('ended', 'Terminé'), ('missed', 'Manqué')], db_index=True, default='ringing', max_length=16)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('callee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calls_received', to=settings.AUTH_USER_MODEL)),
                ('caller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calls_made', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='orders.order')),
            ],
            options={
                'verbose_name': 'appel',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['callee', '-created_at'], name='calls_call_callee__a1c857_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['accepted', 'declined', 'ended', 'missed', 'ringing'])), name='call_status_in_enum'), models.UniqueConstraint(condition=models.Q(('status__in', ['ringing', 'accepted'])), fields=('order',), name='one_active_call_per_order')],
            },
        ),
    ]
