# Generated by Django 5.2.16 on 2026-07-25 14:31

import common.identifiers
import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationPing',
            fields=[
                ('id', models.UUIDField(default=common.identifiers.uuid7, editable=False, primary_key=True, serialize=False)),
                ('point', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('accuracy_m', models.FloatField(blank=True, null=True)),
                ('speed_mps', models.FloatField(blank=True, null=True)),
                ('heading_deg', models.FloatField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_pings', to='delivery.assignment')),
            ],
            options={
                'verbose_name': 'relevé de position',
                'verbose_name_plural': 'relevés de position',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['assignment', '-recorded_at'], name='tracking_lo_assignm_3d534c_idx'), models.Index(fields=['received_at'], name='tracking_lo_receive_7bced8_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('heading_deg__isnull', True), models.Q(('heading_deg__gte', 0), ('heading_deg__lt', 360)), _connector='OR'), name='ping_heading_in_range'), models.CheckConstraint(condition=models.Q(('speed_mps__isnull', True), ('speed_mps__gte', 0), _connector='OR'), name='ping_speed_not_negative')],
            },
        ),
    ]
