# Generated by Django 5.2.16 on 2026-07-26 08:01

import common.identifiers
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VerifiedPurchase',
            fields=[
                ('id', models.UUIDField(default=common.identifiers.uuid7, editable=False, primary_key=True, serialize=False)),
                ('last_purchased_at', models.DateTimeField()),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verified_purchases', to='catalog.menuitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verified_purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'achat vérifié',
                'verbose_name_plural': 'achats vérifiés',
                'constraints': [models.UniqueConstraint(fields=('user', 'menu_item'), name='one_verified_purchase_per_item_and_user')],
            },
        ),
    ]
