# Generated by Django 5.2.16 on 2026-07-29 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_verifiedpurchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Unités restantes. Ignoré tant que le suivi de stock est désactivé.'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='tracks_stock',
            field=models.BooleanField(default=False, help_text='Décompter les commandes du stock. Faux pour un plat préparé à la demande.'),
        ),
    ]
