# Generated by Django 5.2.16 on 2026-08-01 00:30

import common.identifiers
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_menuitem_stock_quantity_menuitem_tracks_stock'),
        ('restaurants', '0003_restaurant_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionTemplate',
            fields=[
                ('id', models.UUIDField(default=common.identifiers.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('group_name', models.CharField(blank=True, help_text="Groupe suggéré à l'application — « Cuisson », « Suppléments ».", max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('price_delta_minor', models.BigIntegerField()),
                ('price_delta_currency', models.CharField(choices=[('EUR', 'EUR'), ('GHS', 'GHS'), ('GNF', 'GNF'), ('NGN', 'NGN'), ('USD', 'USD'), ('XAF', 'XAF'), ('XOF', 'XOF')], default=None, max_length=3)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_templates', to='restaurants.restaurant')),
            ],
            options={
                'verbose_name': "modèle d'option",
                'verbose_name_plural': "modèles d'options",
                'ordering': ['sort_order', 'name'],
                'constraints': [models.UniqueConstraint(fields=('restaurant', 'group_name', 'name'), name='option_template_unique_per_group')],
            },
        ),
    ]
