# Generated by Django 5.2.16 on 2026-08-01 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_optiontemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='optiontemplate',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Présélectionnée dans son groupe une fois appliquée — « à point ».'),
        ),
    ]
