# Generated by Django 5.2.16 on 2026-08-05 20:25

import common.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_optiontemplate_is_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=common.storage.product_images, upload_to='menu/'),
        ),
    ]
