# Generated by Django 5.2.16 on 2026-09-19 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """Modération des avis — masquer, avec motif et auteur.

    La clé étrangère vient **en dernier** : sur une table peuplée, une
    opération `ALTER TABLE` qui suit l'ajout d'une clé différée dans la même
    transaction peut échouer en « pending trigger events » (constaté le
    2026-09-14 sur `orders_order`). Les deux champs simples passent avant elle.
    """

    dependencies = [
        ("catalog", "0006_alter_menuitem_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="hidden_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="review",
            name="hidden_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="review",
            name="hidden_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
