# Generated by Django 5.2.17 on 2026-09-26 20:39

import common.storage
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0008_variantes"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=common.storage.product_images,
                upload_to="categories/",
            ),
        ),
    ]
