# Generated by Django 5.2.16 on 2026-07-27 00:51

import apps.social.models
import common.identifiers
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0004_idempotencykey_completed_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialGroup',
            fields=[
                ('id', models.UUIDField(default=common.identifiers.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('kind', models.CharField(choices=[('family', 'Famille'), ('friends', 'Amis'), ('work', 'Travail'), ('neighborhood', 'Quartier'), ('custom', 'Personnalisé')], default='custom', max_length=16)),
                ('invite_code', models.CharField(default=apps.social.models._invite_code, editable=False, max_length=12, unique=True)),
                ('is_private', models.BooleanField(default=False)),
                ('max_members', models.PositiveIntegerField(default=50)),
                ('member_count', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'groupe social',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=common.identifiers.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('kind', models.CharField(choices=[('order_share', 'Partage de commande'), ('photo', 'Photo'), ('text', 'Texte'), ('event', 'Événement')], default='text', max_length=16)),
                ('image_url', models.URLField(blank=True)),
                ('is_public', models.BooleanField(default=True)),
                ('likes_count', models.PositiveIntegerField(default=0)),
                ('comments_count', models.PositiveIntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_posts', to='orders.order')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='social.socialgroup')),
            ],
            options={
                'verbose_name': 'publication',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.UUIDField(default=common.identifiers.uuid7, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('creator', 'Créateur'), ('admin', 'Administrateur'), ('member', 'Membre')], default='member', max_length=16)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='social.socialgroup')),
            ],
            options={
                'verbose_name': 'adhésion à un groupe',
                'verbose_name_plural': 'adhésions aux groupes',
            },
        ),
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.UUIDField(default=common.identifiers.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_comments', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='social.post')),
            ],
            options={
                'verbose_name': 'commentaire',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['post', 'created_at'], name='social_post_post_id_daac6b_idx')],
            },
        ),
        migrations.CreateModel(
            name='PostLike',
            fields=[
                ('id', models.UUIDField(default=common.identifiers.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='social.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "j'aime",
                'verbose_name_plural': "j'aime",
                'constraints': [models.UniqueConstraint(fields=('post', 'user'), name='one_like_per_user')],
            },
        ),
        migrations.AddConstraint(
            model_name='socialgroup',
            constraint=models.CheckConstraint(condition=models.Q(('max_members__gt', 0)), name='group_capacity_positive'),
        ),
        migrations.AddConstraint(
            model_name='socialgroup',
            constraint=models.CheckConstraint(condition=models.Q(('member_count__lte', models.F('max_members'))), name='group_member_count_within_capacity'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['group', '-created_at'], name='social_post_group_i_a080f5_idx'),
        ),
        migrations.AddConstraint(
            model_name='post',
            constraint=models.CheckConstraint(condition=models.Q(('group__isnull', True), ('is_public', False), _connector='OR'), name='group_post_not_public'),
        ),
        migrations.AddConstraint(
            model_name='post',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'order_share'), _negated=True), ('order__isnull', False), _connector='OR'), name='order_share_has_order'),
        ),
        migrations.AddIndex(
            model_name='groupmembership',
            index=models.Index(fields=['user', 'is_active'], name='social_grou_user_id_f2c39b_idx'),
        ),
        migrations.AddConstraint(
            model_name='groupmembership',
            constraint=models.UniqueConstraint(fields=('group', 'user'), name='one_membership_per_user'),
        ),
    ]
