# Generated by Django 5.2.16 on 2026-07-29 19:18

import common.identifiers
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=common.identifiers.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('body', models.TextField()),
                ('audience', models.CharField(choices=[('all_customers', 'Tous les clients'), ('couriers', 'Tous les livreurs'), ('active_customers', 'Clients ayant commandé récemment'), ('lapsed_customers', 'Clients sans commande récente')], max_length=24)),
                ('segment_days', models.PositiveSmallIntegerField(default=30, help_text='Fenêtre des segments « récemment » et « sans commande récente ».')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('sent', 'Envoyée')], db_index=True, default='draft', max_length=8)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('recipient_count', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'campagne',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='notificatio_status_e901cb_idx')],
            },
        ),
    ]
