# Generated by Django 5.2.16 on 2026-09-18 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_campaign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('order_status', 'Statut de commande'), ('delivery_offer', 'Course proposée'), ('payment', 'Paiement'), ('account', 'Compte'), ('support', 'Service client'), ('marketing', 'Marketing')], db_index=True, max_length=16),
        ),
    ]
