# Generated by Django 5.2.16 on 2026-09-20 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('scheduled', 'Programmée'), ('sent', 'Envoyée')], db_index=True, default='draft', max_length=12),
        ),
    ]
